version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    command: >
      bash -c "
        echo 'Aguardando Kafka...'
        cub kafka-ready -b kafka:29092 1 30
        echo 'Criando tópicos...'
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic faturas.criadas
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic faturas.salvas
        kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 --topic faturas.processadas
        echo 'Tópicos criados com sucesso!'
      "

  producer:
    build:
      context: ./invoice-producer
    ports:
      - 3001:3001
    environment:
      - KAFKA_BROKER=kafka:29092
    depends_on:
      kafka:
        condition: service_started
      kafka-setup:
        condition: service_completed_successfully

  consumer:
    build:
      context: ./invoice-consumer
    ports:
      - 3002:3002
    environment:
      - KAFKA_BROKER=kafka:29092
    volumes:
      - ./shared-data:/usr/src/app/data
    depends_on:
      kafka:
        condition: service_started
      kafka-setup:
        condition: service_completed_successfully

  updater:
    build:
      context: ./invoice-updater
    ports:
      - 3003:3003
    environment:
      - KAFKA_BROKER=kafka:29092
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    volumes:
      - ./shared-data:/usr/src/app/data
    depends_on:
      kafka:
        condition: service_started
      kafka-setup:
        condition: service_completed_successfully

  frontend:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./invoice-frontend:/usr/share/nginx/html
    depends_on:
      - producer
